### ISSUE TITLE
Documentation states golang 1.6+ but won't build with 1.6, requires 1.7

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#770]
The README states 

```
To build and install Consul Template locally, you will need a modern Go (Go 1.6+) environment.
```

But when building the master branch we get errors such as 

```
16 errors occurred:
--> windows/amd64 error: exit status 2
Stderr: # github.com/hashicorp/consul-template/vendor/github.com/hashicorp/vault/api
vendor/github.com/hashicorp/vault/api/client.go:262: undefined: http.ErrUseLastResponse
--> linux/arm error: exit status 2
Stderr: # github.com/hashicorp/consul-template/vendor/github.com/hashicorp/vault/api
vendor/github.com/hashicorp/vault/api/client.go:262: undefined: http.ErrUseLastResponse
--> darwin/386 error: exit status 2
Stderr: # github.com/hashicorp/consul-template/vendor/github.com/hashicorp/vault/api
vendor/github.com/hashicorp/vault/api/client.go:262: undefined: http.ErrUseLastResponse
```

etc

Building w/ 1.7 works
